In [2]:
!pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.7.4-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (9.2 MB)
     |████████████████████████████████| 9.2 MB 1.7 MB/s eta 0:00:01
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.8/site-packages (from matplotlib) (21.0)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.5-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 77.5 MB/s eta 0:00:01
Collecting cycler>=0.10
  Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Collecting contourpy>=1.0.1
  Downloading contourpy-1.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (301 kB)
     |████████████████████████████████| 301 kB 40.1 MB/s eta 0:00:01
Collecting fonttools>=4.22.0
  Downloading fonttools-4.47.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.7 MB)
     |████████████████████████████████| 4.7 MB 70.5 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.8/site-packages (from matplotlib) (2.8.2)
Collecting numpy<2,>=1.20
  Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     |████████████████████████████████| 17.3 MB 28.0 MB/s eta 0:00:01
Collecting importlib-resources>=3.2.0; python_version < "3.10"
  Downloading importlib_resources-6.1.1-py3-none-any.whl (33 kB)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.8/site-packages (from matplotlib) (2.4.7)
Requirement already satisfied: pillow>=6.2.0 in /opt/conda/lib/python3.8/site-packages (from matplotlib) (8.1.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib) (1.15.0)
Collecting zipp>=3.1.0; python_version < "3.10"
  Downloading zipp-3.17.0-py3-none-any.whl (7.4 kB)
Installing collected packages: kiwisolver, cycler, numpy, contourpy, fonttools, zipp, importlib-resources, matplotlib
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.2
    Uninstalling numpy-1.19.2:
      Successfully uninstalled numpy-1.19.2
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

scipy 1.7.1 requires numpy<1.23.0,>=1.16.5, but you'll have numpy 1.24.4 which is incompatible.
Successfully installed contourpy-1.1.1 cycler-0.12.1 fonttools-4.47.0 importlib-resources-6.1.1 kiwisolver-1.4.5 matplotlib-3.7.4 numpy-1.24.4 zipp-3.17.0

In [3]:
import matplotlib.pyplot as plt 
import pandas as pd

In [13]:
def whatType(string):
    dic = eval(string)
    return dic['type']

In [15]:
train_data = pd.read_csv('../data/dataset/train/train.csv')
train_data2 = train_data.copy()
train_data2['object_type'] = train_data2.object_entity.apply(lambda x: whatType(x))
train_data2['subject_type'] = train_data2.subject_entity.apply(lambda x: whatType(x))
train_data2.head()

,id,sentence,subject_entity,object_entity,label,source,object_type,subject_type
0,0,〈Something〉는 조지 해리슨이 쓰고 비틀즈가 1969년 앨범 《Abbey R...,"{'word': '비틀즈', 'start_idx': 24, 'end_idx': 26...","{'word': '조지 해리슨', 'start_idx': 13, 'end_idx':...",no_relation,wikipedia,PER,ORG
1,1,호남이 기반인 바른미래당·대안신당·민주평화당이 우여곡절 끝에 합당해 민생당(가칭)으...,"{'word': '민주평화당', 'start_idx': 19, 'end_idx': ...","{'word': '대안신당', 'start_idx': 14, 'end_idx': 1...",no_relation,wikitree,ORG,ORG
2,2,K리그2에서 성적 1위를 달리고 있는 광주FC는 지난 26일 한국프로축구연맹으로부터...,"{'word': '광주FC', 'start_idx': 21, 'end_idx': 2...","{'word': '한국프로축구연맹', 'start_idx': 34, 'end_idx...",org:member_of,wikitree,ORG,ORG
3,3,균일가 생활용품점 (주)아성다이소(대표 박정부)는 코로나19 바이러스로 어려움을 겪...,"{'word': '아성다이소', 'start_idx': 13, 'end_idx': ...","{'word': '박정부', 'start_idx': 22, 'end_idx': 24...",org:top_members/employees,wikitree,PER,ORG
4,4,1967년 프로 야구 드래프트 1순위로 요미우리 자이언츠에게 입단하면서 등번호는 8...,"{'word': '요미우리 자이언츠', 'start_idx': 22, 'end_id...","{'word': '1967', 'start_idx': 0, 'end_idx': 3,...",no_relation,wikipedia,DAT,ORG

In [21]:
dev_index = train_data2.groupby(['label','object_type','subject_type']).sample(frac=0.5, random_state=777).index
dev_sample = train_data.iloc[dev_index]
train_sample = train_data.drop(dev_index)
dev_sample.shape,train_sample.shape

((16221, 6), (16249, 6))

In [24]:
dev_sample.head()

,id,sentence,subject_entity,object_entity,label,source
15152,15152,1948년 10월 30일부터 대한국민항공사(KNA)에서 서울 - 부산 간 국내선 노...,"{'word': '대한국민항공', 'start_idx': 16, 'end_idx':...","{'word': '1948년', 'start_idx': 0, 'end_idx': 4...",no_relation,wikipedia
18346,18346,입단 첫 해에 당시 감독이었던 김응용의 총애를 받아 김응용이 2001년 삼성 라이온...,"{'word': '삼성 라이온즈', 'start_idx': 40, 'end_idx'...","{'word': '2001년', 'start_idx': 34, 'end_idx': ...",no_relation,wikipedia
28034,28034,1996년 3월 11일 13년간의 노동당 장기집권을 끝내고 총리에 취임하였다.,"{'word': '노동당', 'start_idx': 19, 'end_idx': 21...","{'word': '1996년', 'start_idx': 0, 'end_idx': 4...",no_relation,wikipedia
17620,17620,2012 팔도 프로 야구 한국시리즈는 2012년 10월 24일부터 삼성 라이온즈와 ...,"{'word': '삼성 라이온즈', 'start_idx': 37, 'end_idx'...","{'word': '2012년', 'start_idx': 21, 'end_idx': ...",no_relation,wikipedia
11638,11638,"엎친 데 덮친 격으로 LG 트윈스에서는 선수들 사이의 불화가 끊이지 않았는데, 급기...","{'word': 'KIA 타이거즈', 'start_idx': 68, 'end_idx...","{'word': '2009년', 'start_idx': 48, 'end_idx': ...",no_relation,wikipedia

In [25]:
train_sample.head()

,id,sentence,subject_entity,object_entity,label,source
1,1,호남이 기반인 바른미래당·대안신당·민주평화당이 우여곡절 끝에 합당해 민생당(가칭)으...,"{'word': '민주평화당', 'start_idx': 19, 'end_idx': ...","{'word': '대안신당', 'start_idx': 14, 'end_idx': 1...",no_relation,wikitree
4,4,1967년 프로 야구 드래프트 1순위로 요미우리 자이언츠에게 입단하면서 등번호는 8...,"{'word': '요미우리 자이언츠', 'start_idx': 22, 'end_id...","{'word': '1967', 'start_idx': 0, 'end_idx': 3,...",no_relation,wikipedia
7,7,"박용오(朴容旿, 1937년 4월 29일(음력 3월 19일)(음력 3월 19일) ~ ...","{'word': '박용오', 'start_idx': 0, 'end_idx': 2, ...","{'word': '1937년 4월 29일', 'start_idx': 9, 'end_...",per:date_of_birth,wikipedia
8,8,중공군에게 온전히 대항할 수 없을 정도로 약해진 국민당은 타이베이로 수도를 옮기는 ...,"{'word': '중화민국', 'start_idx': 59, 'end_idx': 6...","{'word': '타이베이', 'start_idx': 32, 'end_idx': 3...",org:place_of_headquarters,wikipedia
9,9,"특히 김동연 전 경제부총리를 비롯한 김두관 국회의원, 안규백 국회의원, 김종민 국회...","{'word': '안규백', 'start_idx': 30, 'end_idx': 32...","{'word': '더불어민주당', 'start_idx': 100, 'end_idx'...",per:employee_of,wikitree

In [26]:
dev_sample.to_csv('../data/dataset/train/dev_sample.csv')
train_sample.to_csv('../data/dataset/train/train_sample.csv')